eureka:
  client:
    service-url:
      defaultZone: http://10.148.0.7:9001/eureka ,http://10.148.0.8:9001/eureka ,http://10.148.0.6:9001/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    lk.ijse.eca: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG