spring:
  mvc:
    problemdetails:
      enabled: true
  data:
    mongodb:
      uri: "mongodb://root:qSybf5F3JUR2GzPReJ4e9ZQf-D8sYqcPNXk7ENDVpnsxgMXf@aa841aae-9a09-4c75-ace8-89653632803f.asia-southeast1.firestore.goog:443/db-capstone?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false"


server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}