spring:
  mvc:
    problemdetails:
      enabled: true
  mongodb:
    uri: "mongodb://root:OcHNRZnK4uR5SGjBtz1fIXh3Uy8zs_7jnh_iGM3BAEIyLJHo@93b021f3-a400-4014-8174-5713c15bd3f4.asia-southeast1.firestore.goog:443/db-capstone?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false"
    auto-index-creation: true

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}